/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:63bf9fcd-05cc-4eaa-ab02-0e79cb612c13",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XL73TDAKs",
    "aws_user_pools_web_client_id": "7o0uts4dj8de2q5i0pnui63841",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "prod-olga-backend-payments155150-prod",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
