/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c3a967fa-dd7e-4dfe-a839-4d2b9d15c1a6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_7Npn25c8F",
    "aws_user_pools_web_client_id": "2n6n3uhscjdoeigvennmni74mt",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "prod-olga-backend-payments155150-prod",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
